WIDGET_PROPERTIES = {
    "population": {"type": "number", "label": "Population", "min": 0, "step": 100},
    "social_orientation": {
        "type": "slider",
        "label": "Social Orientation",
        "min": -100,
        "max": 100,
        "step": 1,
    },
    "economic_orientation": {
        "type": "slider",
        "label": "Economic Orientation",
        "min": -100,
        "max": 100,
        "step": 1,
    },
    "max_political_distance": {
        "type": "slider",
        "label": "Max Political Distance",
        "min": 0,
        "max": 100,
        "step": 1,
    },
    "variety_tolerance": {
        "type": "slider",
        "label": "Variety Tolerance",
        "min": 0,
        "max": 100,
        "step": 1,
    },
    "non_voters_distance": {
        "type": "slider",
        "label": "Non Voters Distance",
        "min": 0,
        "max": 100,
        "step": 1,
    },
    "small_party_distance": {
        "type": "slider",
        "label": "Small Party Distance",
        "min": 0,
        "max": 100,
        "step": 1,
    },
    "ratio_eligible": {
        "type": "slider",
        "label": "Ratio Eligible",
        "min": 0,
        "max": 100,
        "step": 1,
    },
    "political_strength": {
        "type": "slider",
        "label": "Political Strength",
        "min": 0,
        "max": 100,
        "step": 1,
    },
}
